config/routes.rb
UpnLink::Application.routes.draw do

  get "errors/404"
  get "errors/500"

  root :to => 'uploads#new'
  
  resources :users, :except => [ :show ]
  
  resources :uploads
  
  match "/file/:id", :to => 'uploads#show'
  
  resource :session, :controller => 'sessions'
  match '/sign_out', :to => 'sessions#destroy' #, :via => :delete, :as => 'sign_out'  
  resources :users do
    resource :password, :controller => 'passwords'
  end

end

app/views/layouts/_header.html.erb
<% ############################### Up'n'Link Trunk ############################
# Copyright (C) 2012 Jaume Sola - jaumesola.com - upnlink.com
# This software is publicly available under the GPL v3 license terms.
# You may also obtain it under alternative licenses.
# Other files packaged along this one may have a different licensing.
# See the /LICENSE file or http://jaumesola.com/licenses/upnlink.html
############################################################################ %>
<header>
  <nav class="round">
    <ul>
      <% if signed_in? && current_user.admin? -%>
        <li><%= link_to "Upload file", root_path %></li>
        <li><%= link_to 'New User', new_user_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Uploads", uploads_path %></li>
      <% end -%>     
       
      <% if signed_in? -%>
         <li><%= current_user.email %></li>      
         <li><%= link_to "Sign out", sign_out_path, :method => :delete %></li>
        
      <% 
      # Show sign in link only in not this page. In practice never shown.
      elsif ! ( params[:controller] == 'clearance/sessions' and params[:action] == 'new' ) -%>
        <li><%= link_to "Sign in", sign_in_path %></li>
      <% end -%>  

    </ul>
    
  </nav>
</header>

app/views/layouts/application.html.erb
<% ############################### Up'n'Link Trunk ############################
# Copyright (C) 2012 Jaume Sola - jaumesola.com - upnlink.com
# This software is publicly available under the GPL v3 license terms.
# You may also obtain it under alternative licenses.
# Other files packaged along this one may have a different licensing.
# See the /LICENSE file or http://jaumesola.com/licenses/upnlink.html
############################################################################ %>
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.application.config.upnlink_title %></title>

  <!-- Rails  stylesheet_link_tag :all -->
  
  <!-- Blueprint -->
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->  
  
  <!-- YUI -->  
  <link rel="stylesheet" type="text/css" href="/yui-2.9.0/build/fonts/fonts-min.css" />
  
  <!-- Custom -->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>   
<div class="container">
<%= render 'layouts/header' %>

  <section class="round">
     
    <%= link_to logo, Rails.application.config.upnlink_logo_link %>

    <%         
     #flash[:notice] = params[:notice]
     flash.each do |key, value| %>
       <div class="flash <%= key %>"><%= value %></div>
    <% end %>
        
    <%= yield %>

  </section>
  
  <%# render 'layouts/footer' %>
  <%#x debug(params) if Rails.env.development? %>
</div>
</body>
</html>